from django.urls import path
from .views import (
    AdminDashboardStatsView,
    SalesByProductReport,
    OutstandingByStoreReport,
    CollectionsSummaryReport,
    StockExpiryReport,
    LowStockReport,
    StockRequirementsReport,
    CurrentStockSummaryReport,
    StockValuationReport,
    PurchaseHistoryReport,
    PurchaseByProductReport,
    OrderStatusSummaryReport,
    FulfillmentReport,
    InvoiceListReport,
    InvoicesGeneratedReport,
    VoidReport,
    PharmacyOrderSummaryView,
    PharmacyOutstandingView,
    PharmacyInvoiceListView,
)

urlpatterns = [
    path('dashboard-stats/', AdminDashboardStatsView.as_view(), name='admin_dashboard_stats'),
    path('sales-by-product/', SalesByProductReport.as_view(), name='report_sales_by_product'),
    path('outstanding-by-store/', OutstandingByStoreReport.as_view(), name='report_outstanding_by_store'),
    path('collections-summary/', CollectionsSummaryReport.as_view(), name='report_collections_summary'),
    path('stock-expiry/', StockExpiryReport.as_view(), name='report_stock_expiry'),
    path('low-stock/', LowStockReport.as_view(), name='report_low_stock'),
    path('stock-requirements/', StockRequirementsReport.as_view(), name='report_stock_requirements'),
    path('stock-summary/', CurrentStockSummaryReport.as_view(), name='report_stock_summary'),
    path('stock-valuation/', StockValuationReport.as_view(), name='report_stock_valuation'),
    path('purchase-history/', PurchaseHistoryReport.as_view(), name='report_purchase_history'),
    path('purchase-by-product/', PurchaseByProductReport.as_view(), name='report_purchase_by_product'),
    path('order-status-summary/', OrderStatusSummaryReport.as_view(), name='report_order_status_summary'),
    path('fulfillment/', FulfillmentReport.as_view(), name='report_fulfillment'),
    path('invoice-list/', InvoiceListReport.as_view(), name='report_invoice_list'),
    path('invoices-generated/', InvoicesGeneratedReport.as_view(), name='report_invoices_generated'),
    path('void/', VoidReport.as_view(), name='report_void'),
    path('pharmacy/order-summary/', PharmacyOrderSummaryView.as_view(), name='report_pharmacy_order_summary'),
    path('pharmacy/outstanding/', PharmacyOutstandingView.as_view(), name='report_pharmacy_outstanding'),
    path('pharmacy/invoice-list/', PharmacyInvoiceListView.as_view(), name='report_pharmacy_invoice_list'),
]
