# Generated by Django 5.2.11 on 2026-02-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(default="DIRECT", max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="salesman_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="terms",
            field=models.CharField(default="D-CREDIT BILL", max_length=100),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="free_qty",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="gst_rate",
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
    ]
