# Generated by Django 4.2.7 on 2026-02-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_paid_amount_alter_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stock_deducted",
            field=models.BooleanField(default=False),
        ),
    ]
