# Generated by Django 5.2.11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_purchase_status'),
        ('orders', '0005_add_order_item_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orders.orderitem')),
                ('stock_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_allocations', to='products.stockbatch')),
            ],
        ),
    ]
