# Generated by Django 5.2.11 on 2026-02-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_item_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_void',
            field=models.BooleanField(default=False, help_text='Voided orders are excluded from active totals and reports.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_void',
            field=models.BooleanField(default=False, help_text='Voided line items are excluded from order totals.'),
        ),
    ]
