# Generated by Django 5.2.11 on 2026-02-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gst_rate",
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
    ]
