# Generated by Django 5.2.11 on 2026-02-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_gst_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
