# Generated by Django 5.2.11 on 2026-02-14 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="batch_number",
        ),
        migrations.RemoveField(
            model_name="product",
            name="expiry_date",
        ),
    ]
