# Generated by Django 5.2.11 on 2026-02-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_purchase_alter_product_stock_quantity_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.PositiveIntegerField(default=1, help_text='Units per pack (e.g. 10 for strips of 10)'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g. Strip, Box, Piece', max_length=50, null=True),
        ),
    ]
