# Generated by Django 5.2.11 on 2026-02-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_stock_batch_and_purchase_batch_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount per unit applied when ordering', max_digits=10),
        ),
    ]
