# Generated by Django 5.2.11 on 2026-02-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_product_default_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='default_discount',
        ),
        migrations.AddField(
            model_name='product',
            name='default_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage applied when ordering (0-100)', max_digits=5),
        ),
    ]
