# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('approved', 'Approved')],
                default='pending',
                max_length=20,
            ),
        ),
    ]
