# Generated by Django 5.2.11 on 2026-02-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_purchase_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockbatch',
            unique_together={('product', 'batch_number', 'expiry_date')},
        ),
    ]
