# Generated by Django 5.2.11 on 2026-02-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_batch_unique_product_batch_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
